### ISSUE TITLE
Add all games from the latest Ebitengine game jam

### ISSUE THREAD

**Issue by quasilyte** [sedyh/awesome-ebitengine#23]
This is a reminder ticket so we don't forget about it.

https://itch.io/jam/ebitengine-game-jam-2023

**Comment by sedyh** [comment]
| Game | Status |
|----------|----------|
| Sinecord | Added |
| TETRIVERSE | Added |
| Retromancer | Added |
| reverse_gravity | Skipped: unclear launch instructions, unfinished |
| RED CAT RUN 2D | Added |
| The Passage | Added, but the logic behing directions is really confusing |
| Transition | Skipped: unfinished |
| Reverse to the Garage | Skipped, empty readme, confusing to control because wheel turn is not retained enough |
| Siden | Skipped: no launch instructions and the wasm version is broken |
| Reverse Defense | Skipped: no source code found on github |
| Game Engine Development Simulator | Added |
| RevDriller | Added |
| Amaru | Added |
| Reverse Invaders | Skipped: broken controls both on desktop and wasm |
| Reverse Typist | Skipped: no readme |
| Reverset Riders | Added, but gameplay needs proper explanation |
| yamanoteLineGame | Skipped: missing files to go buid, wrong module name and missing files for go run |

* [tetriverse](https://github.com/Critters/TETRIVERSE) - Tetris... in reverse.
* [retromancer](https://github.com/ketMix/retromancer) - Harness the powers of reversing time and fight the Lich in this short action-adventure pseudo bullet-hell game.
* [sinecord](https://github.com/quasilyte/sinecord) - Solve the puzzles and create the music along the way.
* [passage](https://github.com/sjpau/passage) - Small puzzle game. Reverse glyphs to create a passage from * to O.
* [red-cat-run-2d](https://github.com/hinst/red-cat-run-2d) - Become enlightened in this cat platformer game.
* [revdriller](https://github.com/yohamta/revdriller) - Control a character that has a drill, and dig through the ceiling, reverse breakable and unbreakable blocks.
* [reverset-raiders](https://github.com/PrizeLobby/reverset-raiders) - Defeat your enemy by strategically choosing which tiles to flip over to boost the attack of the animals that come towards him.
* [amaru](https://github.com/nmorenor/amaru) - Rid the sea of waste and rescue the trapped marine animals in multiplayer mode.
* [game-engine-dev-sim](https://github.com/hajimehoshi/ebitenginegamejam2023) - Tackle endless bugs and feature requests that relentlessly attack, and strive for a world-class game engine.
