### ISSUE TITLE
Maybe also add a section for books/etc?

### ISSUE THREAD

**Issue by quasilyte** [sedyh/awesome-ebitengine#42]
It would be cool to have https://github.com/tinne26/kage-desk reachable from here.

I use awesome-ebitengine as a rule-of-thumb first link to share with someone interested in Ebitengine so they could get maximum benefits from a single link.

Or maybe we need a separate repo for that and collect tutorials there?

Comments are welcome.

**Comment by sedyh** [comment]
Hello. It's located here: [#wiki](https://github.com/sedyh/awesome-ebitengine?tab=readme-ov-file#wiki).

**Comment by sedyh** [comment]
Would it be better if I removed the wiki and moved it into separate readme entries? 
Perhaps I could redo the navigation on the page. 
Initially, I thought of posting there a comprehensive tutorial on the engine, stitched together from different sources instead of just a list with nested links... Maybe it's worth redesigning the page and making it more visible? For example, add a screenshot of the page to the beginning of the readme.

@quasilyte @tinne26

**Comment by sedyh** [comment]
I've moved wiki internals to the articles section, since quite a few people go there despite the footnote at the beginning of the list.

**Comment by quasilyte** [comment]
I didn't get the CC notification for some reason.

I have no idea why I have some immunity to Github wiki pages. :sweat_smile: 
It's like the moment I learn about the wiki section of the repository, I immediately forget about it.

Maybe it's because 95%+ repositories don't have an active wiki section.
